### ISSUE TITLE
libinstrument.a build failed!

### ISSUE THREAD

**Issue by aceqe** [yrp604/bochscpu-build#1]
Hi,

I build `bochs` on both windows and linux and I get an error when I build `libinstrument`. Can you check it out?

Looks like the make file in the `bochs\instrument\bochscpu` directory doesn't work. I see it like this:
```
libinstrument.a:

clean:
```

Thanks.

**Comment by yrp604** [comment]
Please see the build instructions in the readme.

"
Build
Requires subversion, git, and a C compiler

NOTES:

***by design the build will fail with an error about libinstrument. This is expected and fine.***
"
